services:
  - type: web
    name: ai-traffic-management-smartflow
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    envVars:
      - key: PORT
        value: "8000"
